FROM node:20-alpine

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY package-email.json package.json
RUN npm install --production

# Копируем скрипт
COPY email-listener.js .

# Запуск
CMD ["node", "email-listener.js"]
